language: cpp
sudo: required

matrix:
  include:
    - env: BIONIC= ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - librsvg2-bin
            - libfuse-dev
            - desktop-file-utils
            - ccache
            - libcurl3
            - libbsd-dev
    - env: BIONIC= ARCH=i386
      addons:
        apt:
          update: true
          packages:
            - gcc-multilib
            - g++-multilib
            - libfuse2:i386
            - librsvg2-bin:i386
            - libfuse-dev:i386
            - desktop-file-utils
            - ccache
            - libbsd-dev:i386
            - libglib2.0-dev:i386
            - liblzma-dev:i386
            - libgtest-dev

script:
  - bash -xe travis/travis-build.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh appimaged*.AppImage* appimaged*.deb*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
