language: cpp
sudo: required

matrix:
  include:
    - env: ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - librsvg2-bin
            - libfuse-dev
            - desktop-file-utils
            - ccache
            - libcurl3
            - libbsd-dev
            - libcairo-dev
            - rpm
            - librsvg2-dev
    - env: ARCH=i386
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libfuse2:i386
            - libfuse-dev:i386
            - desktop-file-utils
            - ccache
            - libbsd-dev:i386
            - libglib2.0-dev:i386
            - liblzma-dev:i386
            - libgtest-dev
            - libcairo2-dev:i386
            - librsvg2-bin:i386
            - librsvg2-dev:i386
            - libfreetype6-dev:i386
            - libfontconfig1-dev:i386
            - rpm
            - gir1.2-rsvg-2.0:i386
            - libgdk-pixbuf2.0-dev:i386
            - gir1.2-freedesktop:i386
            - gir1.2-gdkpixbuf-2.0:i386
            - gir1.2-glib-2.0:i386
            - libgirepository-1.0-1:i386

script:
  - ( mkdir -p ./lib ; cd ./lib/ ; git clone --recursive https://github.com/AppImage/libappimage )
  - bash -xe travis/travis-build.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh appimaged*.AppImage* appimaged*.deb* appimaged*.rpm*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
